gitwebgk/amatagroup

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/.default/component_epilog.php
- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/.default/preview_slider.js
- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/.default/template.php
- local/templates/.default/css/style.css
Создан слайдер для превьюх в карточке товара
> Previews slider created

- local/templates/.default/js/main.js
Был трабл со сваливанием ползунков в кучу при переключении вкладок
> Пофикшен баг в слайдере цены в умном фильтре

- local/templates/.default/components/bitrix/catalog.section/favourite/template.php
- local/templates/.default/css/style.css
- personal/favourite/index.php
> Пофиксил табы в избранном

- ajax/saved_addresses_handling.php
- local/php_interface/init.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/delivery.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/lang/ru/template.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/props.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/props_format.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/template.php
- local/templates/.default/js/main.js
Реализовано:
переключение сохраненных профилей
выбор среди сохраненных адресов
> Доработки по профилю и сохраненным адресам

- local/php_interface/init.php
Добавлена функция проверки на существование сохраненного адреса
> Добавлена функция проверки на существование сохраненного адреса

- local/templates/.default/js/main.js
Фикс бага с сердечком, когда пользователь неавторизован
> Фикс мелких багов

- local/templates/.default/components/bitrix/sale.order.ajax/order/confirm.php
- local/templates/.default/css/style.css
Стилизация страницы подтверждения заказа
> Стилизация страницы подтверждения заказа

- local/templates/.default/components/bitrix/system.auth.form/popup_auth/template.php
- local/templates/.default/css/style.css
- local/templates/.default/js/main.js
Фикс бага с текстом авторизации во всплывающей форме
> Фикс бага с текстом авторизации во всплывающей форме

- local/templates/.default/js/main.js
Фикс бага с выпадающим списком торговых предложений
> Фикс бага с выпадающим списком торговых предложений

- local/php_interface/init.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/delivery.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/lang/ru/template.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/props_format.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/template.php
1 ) Больше не происходит сохранения адреса при выборе самовывоза
2) Форма добавления нового адреса по-умолчанию скрыта, для ее отображения есть лейбл "Добавление нового адреса"
3) Для самовывоза есть контейнер с инструкциями по самовывозу
> Фикс проблем с сохраненными адресами

- local/templates/.default/js/main.js
Фикс бага с переключением верхнего меню
> Фикс бага с переключением верхнего меню

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.section/table/template.php
- local/templates/.default/js/main.js
Фикс бага с лейблом "в наличии" для табличного отображения каталога
> Фикс бага с лейблом "в наличии" для табличного отображения каталога

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/.default/template.php
Если у товара есть ТП, то первое будет автоматически выбрано. Сделано для карточки товара
> Переработка вывода для товара с предложениями

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.section/table/template.php
Если у товара есть ТП, то первое будет автоматически выбрано. Сделано для списка товаров
> Если у товара есть ТП, то первое будет автоматически выбрано

- local/templates/.default/components/bitrix/news/news_tabs/detail.php
- local/templates/.default/components/bitrix/news/news_tabs/news.php
- local/templates/amatagroup_inner/header.php
- news/index.php
- urlrewrite.php
Фикс проблемы с хк для детальной новости
> Фикс проблемы с хк для детальной новости

- local/templates/.default/components/bitrix/news.list/partners_reviews/template.php
- local/templates/amatagroup_index/header.php
Все верстка перенесена внутрь и стрелки не отображаются, если элементов больше 4
> Правки для отзывов партнеров.

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/.default/template.php
- local/templates/.default/js/main.js
Создана вкладка "Файлы" в карточке товара
> Создана вкладка "Файлы" в карточке товара

- catalog/index.php
- local/php_interface/init.php
- local/templates/.default/css/style.css
- local/templates/.default/include/header.php
- local/templates/.default/js/main.js
- urlrewrite.php
Автоопределение города реализовано
> Автоопределение города реализовано

- about/index.php
- ajax/add-question.php
- local/php_interface/init.php
- local/templates/.default/css/style.css
- local/templates/.default/js/main.js
Реализована форма создания вопроса в разделе о компании
> Реализована форма создания вопроса

- about/index.php
- ajax/add-question.php
- local/templates/.default/js/main.js
1 - Убран лог
2 - поправлены паттерны валидации
3 - Исправлена кодировка при записи в БД
> Небольшие доработки формы

- local/templates/.default/css/style.css
Небольшой фикс стилей для раздела новости
> Небольшой фикс стилей для раздела новости

- local/templates/.default/components/bitrix/catalog.smart.filter/catalog_filter/template.php
> Фикс для умного фильтра

- local/templates/.default/components/bitrix/news/news_without_tabs/detail.php
> Фикс проблемы с хк в новостях

- local/templates/.default/components/bitrix/news.list/retail/result_modifier.php
- local/templates/amatagroup_catalog/footer.php
- local/templates/amatagroup_catalog/lang/ru/footer.php
- local/templates/amatagroup_inner/lang/ru/footer.php
Фикс lang для футера внутренних
> Фикс lang для футера внутренних

- local/templates/.default/include/header.php
- local/templates/amatagroup_inner/footer.php
Фикс футера для внутренних страниц и баннера для главной
> Фикс футера для внутренних страниц и баннера для главной

- personal/cart/index.php
> Фикс краша в корзине

- urlrewrite.php
> Фикс краша в разделе акции

- local/php_interface/init.php
- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/.default/component_epilog.php
- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/.default/template.php
- local/templates/.default/css/style.css
- local/templates/.default/js/main.js
Изображения теперь уменьшаются php при выводе, центруются и главную картинку можно увеличить
> Переработка вывода изображений в карточке

- local/templates/.default/components/bitrix/sale.personal.order.list/.default/lang/ru/template.php
- local/templates/.default/components/bitrix/sale.personal.order.list/.default/result_modifier.php
- local/templates/.default/components/bitrix/sale.personal.order.list/.default/template.php
> CP-4073: правки по шаблону

- ajax/leave_question_catalog.php
- local/php_interface/init.php
- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/.default/lang/ru/template.php
- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/.default/template.php
1) Доработан шаблон
2) Рефакторинг
3) Сделаны доработки функционала
> Переработка формы в карточке товара

- local/templates/.default/js/main.js
Фикс бага с показом/сокрытием меню
> Фикс бага с показом/сокрытием меню

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/.default/template.php
- local/templates/.default/js/main.js
Вывод дополнительных фото ТП в превью
> Вывод дополнительных фото ТП в превью

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/.default/template.php
PREVIEW_PICTURE => DETAIL_PICTURE
> Изменен источник новых картинок для превью

- brands/index.php
- local/php_interface/init.php
- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/.default/result_modifier.php
- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/.default/template.php
- local/templates/.default/components/bitrix/news/brands/bitrix/news.detail/.default/template.php
- local/templates/.default/components/bitrix/news/brands/detail.php
- local/templates/.default/css/style.css
1) Создана ссылка на детальную страницу бренда
2) Бренд включен в цепочку навигации
3) Заголовок у брендов приведен к стилю сайта
> Доработки по брендам

- about/.section.php
- about/index.php
- ajax/add-faq-question.php
- ajax/add-question.php
- local/php_interface/init.php
- local/templates/.default/css/style.css
- local/templates/.default/js/main.js
- questions/index.php
1) Создан шаблон письма для форм из /about и /question
2) Поправлена валидация
3) Добавлена всплывающая форма при сабмите
4) Мелкие правки
> Доработка форм

- local/templates/.default/css/style.css
- local/templates/.default/js/main.js
> CP-4122: правка формы регистрации

- auth/index.php
- local/templates/.default/css/style.css
- local/templates/.default/js/main.js
> CP-4122: прпавки

- ajax/smallBasket.php
- local/php_interface/init.php
- local/templates/.default/components/bitrix/catalog.section/bestsellers/template.php
- local/templates/.default/components/bitrix/catalog.section/blocks/template.php
- local/templates/.default/components/bitrix/catalog.section/catalog_blog/template.php
- local/templates/.default/components/bitrix/catalog.section/product_news/template.php
- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.section/blocks/template.php
- local/templates/.default/components/bitrix/sale.basket.basket.small/small_basket/template.php
- local/templates/.default/css/style.css
- local/templates/.default/include/footer.php
- local/templates/.default/js/main.js
- test.php
> CP-4008: правки

- ajax/mailing.php
> SUP-4811: правка подписки

- catalog/index.php
- local/templates/.default/include/header.php
> SUP-4811: правка страницы каталога

- local/templates/.default/components/bitrix/catalog.section.list/catalog_menu/template.php
- local/templates/.default/css/style.css
Исправлено мигание главного меню при загрузке страницы
> Фикс мигания главного меню

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/.default/template.php
- local/templates/.default/js/main.js
Изменение выбранного превью, при изменении ТП
> Изменение выбранного превью, при изменении ТП

- local/templates/.default/css/style.css
Фикс выравнивания картинок в брендах
> Фикс выравнивания картинок в брендах

- local/templates/.default/js/main.js
> CP-4371: Выбор ТП после клика по превьюхе

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.section/table/style.css
- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.section/table/template.php
- local/templates/.default/css/style.css
- local/templates/.default/js/main.js
> CP-4371: Выбор соответствующей превьюшки, при переключении ТП

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/.default/template.php
- local/templates/.default/css/style.css
правка нижней границы в карточке товара
> CP-4371: правка нижней границы в карточке товара

- local/templates/.default/components/bitrix/catalog.smart.filter/catalog_filter/lang/ru/template.php
- local/templates/.default/components/bitrix/catalog.smart.filter/catalog_filter/style.css
- local/templates/.default/components/bitrix/catalog.smart.filter/catalog_filter/template.php
- local/templates/.default/js/main.js
изменение вывода свойств фильтра
> CP-4412: изменение вывода свойств фильтра

- local/templates/.default/components/bitrix/catalog.smart.filter/catalog_filter/template.php
> CP-4412: правка сссылки

- local/templates/.default/components/bitrix/catalog.viewed.products/section_viewed/template.php
- local/templates/.default/components/bitrix/catalog/catalog/section.php
Код перемещен из section.php в /local/templates/.default/components/bitrix/catalog.viewed.products/section_viewed/template.php
> CP-4413: Перенос кода просмотренных товаров в шаблон компонента

- local/templates/.default/css/style.css
При насадке нарушилась иерархия, заданная в стилях верстки
> CP-4411: Исправление отображения лейблов в карточке

- local/php_interface/init.php
- local/php_interface/ru/init.php
- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.section/blocks/template.php
- local/templates/.default/components/bitrix/catalog/catalog/section.php
- local/templates/.default/css/style.css
- local/templates/.default/js/main.js
добавление фильтра на наличие товара в каталге
> SUP-5086: добавление фильтра на наличие товара в каталге

- local/templates/.default/css/style.css
> SUP-5086: правка стиля кнопки в наличии

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/.default/template.php
изменение вывода ссылки подробнее
> SUP-5162: изменение вывода ссылки подробнее

- news_product.php
изменение времени вывода новинок
> SUP-5166: изменение времени вывода новинок

- local/templates/.default/js/main.js
изменение условия скрытия блоков
> SUP-5166: изменение условия скрытия блоков

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/.default/template.php
- local/templates/.default/include/header.php
удаление рамки при отсутствии фото
> CP-4533: удаление рамки при отсутствии фото

- local/templates/.default/components/bitrix/news/brands/bitrix/news.list/.default/style.css
- local/templates/.default/include/header.php
- personal/order/make/index.php
добавление редиректа на страницу оформления заказа и изменение стилей в разделе брендов
> CP-4533: добавление редиректа на страницу оформления заказа и изменение стилей в разделе брендов 

- local/templates/.default/components/bitrix/main.register/popup_register/template.php
- local/templates/.default/components/bitrix/system.auth.form/popup_auth/ajax.php
- local/templates/.default/js/main.js
изменение класса в js при авторизации
> CP-4533: изменение класса в js при авторизации

- local/templates/.default/components/bitrix/sale.order.ajax/order/auth.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/lang/ru/template.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/style.css
- local/templates/amatagroup_index/components/bitrix/system.auth.form/eshop_adapt_auth/template.php
- personal/order/make/index.php
правки страницы авторизации при оформлении заказа
> CP-4533: правки страницы авторизации при оформлении заказа

- local/templates/.default/components/bitrix/catalog.section/slider_main/lang/ru/template.php
- local/templates/.default/components/bitrix/catalog.section/slider_main/style.css
- local/templates/.default/components/bitrix/catalog.section/slider_main/template.php
> SUP-5193: добавление кнопки на баннер

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/new_layout/template.php
- local/templates/.default/css/style.css
изменение блока в карточке товара
> CP-4533: изменение блока в карточке товара

- catalog/news_product/index.php
- local/templates/amatagroup_index/header.php
изменение вывода товаров за 30 дней
> SUP-5167: изменение вывода товаров за 30 дней

- local/templates/.default/components/bitrix/catalog.section/slider_main/style.css
- local/templates/.default/components/bitrix/catalog.section/slider_main/template.php
> SUP-5193: добавление ссылки на баннер

- local/templates/.default/css/style.css
правка стилей в разделе о компании
> SUP-5271: правка стилей в разделе о компании

- local/templates/.default/components/bitrix/main.feedback/back_call/style.css
- local/templates/.default/components/bitrix/main.feedback/back_call/template.php
> SUP-5258: правка стилей формы звонка

- prices/index.php
Добавление включаемой области на странице остатков.
> SUP-5290: adding included area

- local/templates/.default/include/meta.php
добавление Google Maps API-ключа к подключению Google карт
> SUP-5292: добавление Google Maps API-ключа к подключению Google карт

- local/templates/.default/components/bitrix/catalog.section.list/catalog_menu/style.css
- local/templates/.default/components/bitrix/catalog.section.list/catalog_menu/template.php
- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/new_layout/component_epilog.php
- local/templates/.default/components/bitrix/catalog/catalog/element.php
- local/templates/.default/components/bitrix/catalog/catalog/section.php
- local/templates/.default/js/main.js
добавлен алгоритм раскрытия нужных разделов каталога в меню при его открытии
> SUP-5165: доработка скрипта раскрытия меню каталога

- local/templates/.default/components/bitrix/news/brands/bitrix/news.list/.default/style.css
- local/templates/.default/components/bitrix/news/brands/bitrix/news.list/.default/template.php
изменение стилей и алфавита брендов
> CP-4533: изменение стилей и алфавита брендов

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.search/.default/template.php
отключение раскладки при поиске товаров
> SUP-5317: отключение автоматической смены раскладки при поиске товаров

- local/templates/.default/components/bitrix/catalog/catalog/section.php
Редактирование настроек компонента catalog.section.list (отключение добавления раздела в цепочку навигации)
> SUP-5165: редактирование настроек компонента catalog.section.list

- ajax/leave_question_catalog.php
- local/php_interface/init.php
добавление нового шаблона письма
> SUP-5251: добавление нового шаблона письма

- local/templates/amatagroup_index/header.php
изменение сортировки новинок на рандомную
> SUP-5167: изменение сортировки новинок на рандомную

- urlrewrite.php
добалвнеие правила для страницы новостей
> SUP-5278: добалвнеие правила для страницы новостей

- about/index.php
- local/php_interface/init.php
- local/templates/.default/components/bitrix/news.list/achievements/result_modifier.php
- local/templates/.default/components/bitrix/news.list/achievements/template.php
добавление блока в раздел Сертификаты дистрибьютера
> SUP-5347: добавление блока в раздел Сертификаты дистрибьютера 

- local/templates/.default/components/bitrix/catalog.section.list/catalog_menu/template.php
- local/templates/.default/css/style.css
- local/templates/.default/js/main.js
изменение открытия ссылок в меню каталога
> SUP-5357: изменение открытия ссылок в меню каталога

- about/index.php
правки для блок для картинок в разделе о компании
> SUP-5347: правки для блок для картинок в разделе о компании

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/new_layout/component_epilog.php
- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/new_layout/template.php
- local/templates/.default/js/main.js
редактирование блока просмотра картинки в модальном окне (возможность перелистывания всех доп.картинок товара)
> SUP-5355: редактирование блока просмотра картинки в модальном окне

- local/templates/.default/components/bitrix/catalog.section/arrivals/template.php
- local/templates/.default/components/bitrix/catalog.section/bestsellers/template.php
- local/templates/.default/components/bitrix/catalog.section/blocks/template.php
- local/templates/.default/components/bitrix/catalog.section/catalog_blog/template.php
- local/templates/.default/components/bitrix/catalog.section/favourite/template.php
- local/templates/.default/components/bitrix/catalog.section/latest/template.php
- local/templates/.default/components/bitrix/catalog.section/product_news/template.php
- local/templates/.default/components/bitrix/catalog.section/section_catalog/template.php
изменение логотипа в блоках на главной странице
> SUP-5167: изменение логотипа в блоках на главной странице

- local/php_interface/init.php
- local/templates/.default/css/style.css
- news/index.php
> SUP-5367: правки в отображении новостей

- local/templates/.default/css/style.css
правка стилей меню для firefox
> SUP-5392: правка стилей меню для firefox

- local/templates/.default/components/bitrix/sale.basket.basket/basket/basket_items.php
- local/templates/.default/components/bitrix/sale.basket.basket/basket/component_epilog.php
- local/templates/.default/components/bitrix/sale.basket.basket/basket/template.php
исправление бага с дублированием просмотренных товаров в корзине
> SUP-5379: исправление бага с дублированием просмотренных товаров в корзине

- local/templates/.default/components/bitrix/catalog.section/favourite/template.php
исправление страницы избранного
> SUP-5379: исправление страницы избранного

- personal/favourite/index.php
удаление лишнего блока просмотренных товаров
> SUP-5379: удаление лишнего блока просмотренных товаров

- local/templates/.default/components/bitrix/catalog.section/slider_main/template.php
- local/templates/.default/components/bitrix/sale.basket.basket/basket/basket_items.php
- local/templates/.default/components/bitrix/sale.basket.basket/basket/script.js
изменение символа цены в корзине и баннере
> SUP-5377: изменение символа цены в корзине и баннере

- catalog/latest_product/index.php
- local/templates/.default/components/bitrix/catalog.section/arrivals/template.php
- local/templates/.default/components/bitrix/catalog.section/bestsellers/template.php
- local/templates/.default/components/bitrix/catalog.top/bestsellers/lang/ru/template.php
- local/templates/.default/components/bitrix/catalog.top/bestsellers/template.php
- local/templates/.default/components/bitrix/catalog/catalog_new_product/bitrix/catalog.section/blocks/template.php
- local/templates/.default/components/bitrix/catalog/catalog_new_product/sections.php
- local/templates/amatagroup_index/header.php
изменение свойства хитов продаж
> SUP-5177: изменение свойства хитов продаж

- catalog/bestsellers/index.php
- local/php_interface/init.php
- local/templates/.default/components/bitrix/catalog.section/arrivals/template.php
- local/templates/.default/components/bitrix/catalog.section/bestsellers/template.php
- local/templates/.default/components/bitrix/catalog/catalog_new_product/bitrix/catalog.section/blocks/template.php
- local/templates/amatagroup_index/header.php
изменение логики вывода хитов продаж
> SUP-5177: изменение логики вывода хитов продаж

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/new_layout/template.php
доработка rel атрибутов для ссылок картинок и доработка ресайзинга
> SUP-5355: доработка rel атрибутов для ссылок картинок и доработка ресайзинга

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/new_layout/template.php
добавление rel атрибута к картинкам торговых предложений, ресайзинг главной картинки товара
> SUP-5355: добавление rel атрибута к картинкам торговых предложений, ресайзинг главной картинки товара

- local/php_interface/init.php
> SUP-5377: изменение письма заказа

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/new_layout/template.php
ресайзинг картинок торговых предложений
> SUP-5355: ресайзинг картинок торговых предложений

- local/templates/amatagroup_index/header.php
изменение фильтра на главной у брендов
> SUP-5407: изменение фильтра на главной у брендов

- local/templates/.default/components/bitrix/sale.basket.basket/basket/script.js
- local/templates/.default/components/bitrix/sale.basket.basket/basket/style.css
- local/templates/.default/components/bitrix/sale.basket.basket/basket/template.php
изменение строки вывода предупреждения о количестве товара
> SUP-5395: изменение строки вывода предупреждения о количестве товара

- local/php_interface/init.php
изменение события при отправке заказа
> SUP-5377: изменение события при отправке заказа

- about/index.php
- brands/index.php
- local/templates/.default/components/bitrix/news/brands/bitrix/news.list/.default/template.php
- local/templates/.default/css/style.css
- local/templates/amatagroup_index/header.php
УДАЛЕНИЕ по ограничения наличию картинок в брендах
> 	SUP-5422: удаленеие фильтра по наличию картинок в брендах

- catalog/news_product/index.php
- local/php_interface/init.php
- local/templates/amatagroup_index/header.php
изменение количества дней для наовинок
> SUP-5437: изменение количества дней для новинок

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.section/blocks/template.php
- local/templates/.default/components/bitrix/catalog/catalog/section.php
- local/templates/.default/components/bitrix/main.register/popup_register/template.php
- local/templates/.default/css/style.css
Фикс для IE:
- починили уехавший фильтр в каталоге
- убрана белая полоска в футере в каталоге
Общие исправления
- закрыты недостающие теги
- фикс постранички слайдера для главной
- фикс развалившихся просмотренных товаров внизу секции товаров
> CP-4686: Много мелких правок

- local/templates/.default/components/bitrix/catalog.section/slider_main/template.php
добавление символа рубля в слайдере
> SUP-5448: добавление символа рубля в слайдере

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/new_layout/component_epilog.php
- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/new_layout/template.php
- vendor/fancybox/jquery.fancybox.css
Изменил скорость, картинки не повторяются, превью не вылезают.
> SUP-5355: Доработка слайдера в элементе каталога

- local/templates/.default/components/bitrix/news/news_without_tabs/bitrix/news.detail/.default/lang/ru/template.php
- local/templates/.default/components/bitrix/news/news_without_tabs/bitrix/news.detail/.default/style.css
- local/templates/.default/components/bitrix/news/news_without_tabs/bitrix/news.detail/.default/template.php
- local/templates/.default/components/bitrix/news/news_without_tabs/bitrix/news.list/.default/lang/ru/template.php
- local/templates/.default/components/bitrix/news/news_without_tabs/bitrix/news.list/.default/style.css
- local/templates/.default/components/bitrix/news/news_without_tabs/bitrix/news.list/.default/template.php
изменение стиля отображения активности акций
> SUP-5434: изменение стиля отображения активности акций

- catalog/bestsellers/index.php
- local/templates/.default/components/bitrix/catalog/catalog_new_product/element.php
- local/templates/.default/components/bitrix/catalog/catalog_new_product/section.php
- local/templates/.default/components/bitrix/catalog/catalog_new_product/sections.php
изменение ссылок для детальной странице в разделе каталога
> SUP-5461: изменение ссылок для детальной странице в разделе каталога

- auth/registration/index.php
- local/components/webgk/register_amata/templates/.default/template.php
- local/templates/.default/css/style.css
добавление дополнительного поля на страницу регистрации
> SUP-5470: добавление дополнительного поля на страницу регистрации

- local/components/webgk/register_amata/component.php
добавление дополнительных полей в письмо, прикрепление файлов
> SUP-5438: добавление дополнительных полей в письмо, прикрепление файлов

- local/components/webgk/register_amata/templates/.default/template.php
- local/templates/.default/js/main.js
> SUP-5470: правки поля название компании

- local/templates/.default/css/style.css
правка стиле блока бестселлеры
> SUP-5487: правка стиле блока бестселлеры

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/new_layout/lang/ru/template.php
- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/new_layout/template.php
- local/templates/.default/css/style.css
- local/templates/.default/js/main.js
редактирование блока количества товара
> SUP-5485: редактирование блока количества товара

- local/templates/.default/components/bitrix/news/news_without_tabs/bitrix/news.detail/.default/template.php
доработки детальной страницы новостей
> SUP-5476: доработки детальной страницы новостей

- local/templates/.default/js/blocks_titles_shave_script.js
Фикс для ситуаций, когда очень длинные названия не влезали во всплывающие блоки
> SUP-5500: Фикс для всплывающих названий

- local/templates/.default/components/bitrix/news/news_without_tabs_promo/bitrix/news.list/.default/result_modifier.php
- local/templates/.default/components/bitrix/news/news_without_tabs_promo/bitrix/news.list/.default/template.php
добавление активности в разделы страницы акций
> SUP-5458: добавление активности в разделы страницы акций

- local/php_interface/init.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/delivery.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/template.php
- urlrewrite.php
> SUP-5502: добавление пунктов самовывоза

- local/templates/.default/css/style.css
> SUP-5488: правка стилей в блоке отзывов

- local/templates/.default/components/bitrix/catalog.section/expected_products/template.php
- local/templates/.default/components/bitrix/catalog.section/product_news/template.php
- local/templates/.default/components/bitrix/catalog.top/bestsellers/template.php
- local/templates/.default/css/style.css
1) Добавлен вывод полного названия в data атрибут у слайдеров на главной
2) Исправлен overflow у слайдеров в карточке
> SUP-5390: Фикс мелких багов

- local/templates/.default/css/style.css
> SUP-5497: правка стилей фильтра

- local/templates/.default/components/bitrix/catalog/catalog/search.php
- local/templates/.default/include/header.php
изменение свойств поиска по товарам
> SUP-5444: изменение свойств поиска по товарам

- local/templates/.default/components/bitrix/news.list/partners_reviews/template.php
> SUP-5488: правка вывода свойств

- local/templates/.default/js/main.js
вывод ошибки при заполнении поля меньше 6 символов
> SUP-5438: вывод ошибки при заполнении поля меньше 6 символов

- local/templates/.default/css/style.css
корректировка фонового цвета для блока "Мы доверяем"
> SUP-5526: корректировка фонового цвета для блока "Мы доверяем"

- local/templates/.default/css/style.css
корректировка фонового цвета для блока брендов
> SUP-5529: корректировка фонового цвета для блока брендов

- brands/index.php
- local/php_interface/init.php
Требуется создание у инфоблока брендов свойства HAVE_PRODUCTS
> SUP-5538: Запрет на вывод брендов без товаров

- local/templates/.default/components/bitrix/news.list/retail/style.css
- local/templates/.default/js/main.js
редактирование стилей страницы "где купить"
> SUP-5644: редактирование стилей страницы "где купить"

- local/components/webgk/register_amata/component.php
- local/templates/.default/js/main.js
изменение путей файлов в массиве
> SUP-5649: изменение путей файлов в массиве

- local/php_interface/init.php
добавление свойства брендов в раздел брендов
> SUP-5612: добавление свойства брендов в раздел брендов

- local/templates/amatagroup_index/header.php
Включили кеш с периодом 4 часа для bitrix:catalog.section на главной странице
> SUP-5658: Включение кеша для компонентов индексной страницы

- local/templates/.default/components/bitrix/news.list/confidens/preview_slider.js
- local/templates/.default/components/bitrix/news.list/confidens/template.php
- local/templates/.default/css/style.css
- local/templates/.default/include/header.php
- local/templates/amatagroup_index/header.php
> SUP-5668: правка слайдера на главной

- local/templates/.default/components/bitrix/news.list/confidens/template.php
- local/templates/.default/css/style.css
> SUP-5668: изменение слайдера

- local/templates/.default/css/style.css
> SUP-5668: изменение стиля

- local/templates/.default/components/bitrix/catalog/catalog/bitrix/catalog.element/new_layout/template.php
корректировка ссылки с картинки карточки товара (вывод полноразмерной картинки предложения в попап-окне)
> SUP-5685: корректировка ссылки с картинки карточки товара

- include/history.php
- local/templates/amatagroup_inner/template_styles.css
> SUP-5364: правки по верстке о компании

- local/components/webgk/register_amata/component.php
- local/templates/.default/js/main.js
изменение скрипта добавления файла
> SUP-5682: изменение скрипта добавления файла

- local/templates/.default/components/bitrix/news/brands/bitrix\news.detail\.default\template.php
- local/templates/amatagroup_inner/header.php
- local/templates/amatagroup_inner/lang/ru/header.php
изменение заголовка у детальных брендов
> SUP-5725: изменение заголовка у детальных брендов
